7. -- How much sales revenue was generated by each product category?

SELECT 
    category, SUM(line_sales_inr) AS sales_revenue
FROM
    order_items ot
        JOIN
    products p ON ot.product_id = p.product_id
GROUP BY category;

8. -- Which 5 products generated the highest sales revenue?

SELECT 
    product_name, SUM(line_sales_inr) AS sales_revenue
FROM
    order_items ot
        JOIN
    products p ON ot.product_id = p.product_id
GROUP BY product_name
ORDER BY sales_revenue DESC
LIMIT 5;


9.-- How many orders were placed by customers in each customer segment?

SELECT 
    customer_segment, COUNT(order_id) AS order_count
FROM
    orders o
        JOIN
    customers c ON o.customer_id = c.customer_id
GROUP BY customer_segment;

10.-- How much sales revenue was generated in each region?

SELECT 
    l.region, SUM(line_sales_inr) AS sales_revenue
FROM
    customers c
        JOIN
    locations l ON c.location_id = l.location_id
        JOIN
    orders o ON c.customer_id = o.customer_id
        JOIN
    order_items ot ON ot.order_id = o.order_id
GROUP BY l.region

ORDER BY sales_revenue DESC;

11.-- Which products have an average customer rating greater than 4?

SELECT 
    product_name, AVG(rating) AS average_customer_rating
FROM
    reviews r
        JOIN
    order_items oi ON r.order_item_id = oi.order_item_id
        JOIN
    products p ON oi.product_id = p.product_id
GROUP BY product_name
HAVING average_customer_rating > 4;

12. -- How much sales revenue was generated in each month?

SELECT 
    YEAR(o.order_date) AS year,
    MONTH(o.order_date) AS month,
    SUM(line_sales_inr) AS sales_revenue
FROM
    order_items oi
        JOIN
    orders o ON oi.order_id = o.order_id
GROUP BY 
YEAR(o.order_date),
MONTH(o.order_date)
ORDER BY 
YEAR(o.order_date), 
MONTH(o.order_date);

13. -- Classify each order into a value category based on its total sales revenue:

SELECT 
    o.order_id,
    SUM(oi.line_sales_inr) AS sales_revenue,
    CASE
        WHEN SUM(oi.line_sales_inr) < 5000 THEN 'Low value'
        WHEN SUM(oi.line_sales_inr) BETWEEN 5000 AND 10000 THEN 'Medium value'
        ELSE 'high value'
    END AS order_value_category
FROM
    orders o
        JOIN
    order_items oi ON oi.order_id = o.order_id
GROUP BY o.order_id
ORDER BY o.order_id;